@echo off
set "t=%time%"
echo.
echo Hello World
echo.
echo.
echo.
echo Tool Name: CSV to mf4 converter
echo.
echo Author: RBCD/ESD Tang Zhongji
echo This tool reqires excel and mdfwriter
echo.
echo Usage:
echo. 1.     Put this file inside the top folder where CSV files generated by CCU
echo. 2.     Double click the batfile
echo. 3.     Done, the mf4 files will in another called Outdata.
echo.
echo.
cd /d %~dp0
if not exist makemf4.xlsm echo "Cannot find macros in makef4.xlsm, please check it" && pause && exit
if not exist csvfile md csvfile
if not exist mf4file md mf4file
set tmpVbs=nsbb.vbs
more +39 %0 >%tmpVbs%
for /f "tokens=*" %%a in (
 'dir /b/a-d/s *.csv '
) do (
echo Converting %%~nxa
 cscript //Nologo "%tmpVbs%" "%%~dpnxa" 
)
del "%tmpVbs%" /q 1>nul 2>nul
echo Everything done.
set "t1=%time%"
if "%t1:~,2%" lss "%t:~,2%" set "add=+24"
set /a "times=(%t1:~,2%-%t:~,2%%add%)*360000+(1%t1:~3,2%%%100-1%t:~3,2%%%100)*6000+(1%t1:~6,2%%%100-1%t:~6,2%%%100)*100+(1%t1:~-2%%%100-1%t:~-2%%%100)" ,"ss=(times/100)%%60","mm=(times/6000)%%60","hh=times/360000","ms=times%%100"
echo Script running time: %hh%:%mm%:%ss%.%ms%
pause
Exit
'Const xlCSV = 6
'dim filepathname
Filename = WScript.Arguments.Unnamed.Item(0)
currFolder=createobject("Scripting.FileSystemObject").GetFile(Wscript.ScriptFullName).ParentFolder.Path
repname=replace(replace(Filename,"csvfile","mf4file"),".csv",".mf4")
Foldername=replace(left(Filename,instrrev(Filename,"\")-1), "csvfile", "mf4file")
'wscript.echo "Filename: " & Filename
'wscript.echo "repname: " & repname
'wscript.echo "Foldername: " & Foldername
Set Objectfs = CreateObject("Scripting.FileSystemObject")
'wscript.echo repname


If not Objectfs.FileExists(currFolder & "\makemf4.xlsm") Then
	wscript.echo "Cannot find file 'makemf4.xlsm, please check.'"
	wscript.quit
end if
If Objectfs.FileExists(repname) Then
wscript.echo ".mf4 already exists, skip..."
wscript.echo ""
wscript.echo ""
wscript.quit
end if
wscript.echo "New file deceted, generating mf4 file."
'on error resume next
Set objExcel = CreateObject("Excel.Application")
Set objWorkbook = objExcel.Workbooks.Open(Filename)
set objSheet=objWorkbook.activesheet
on error resume next

	set macbook=objExcel.Workbooks.Open(currFolder & "\makemf4.xlsm")

objExcel.run "makemf4" ,objWorkbook, objSheet, "csvfile","mf4file"
'macbook.close false
REM filepathname = objWorkbook.path & "\\converted\\" & mid(Filename,1,len(Filename)-4) & ".csv"
'objWorkbook.close false
if wscript.Err.number<>0 then
	'wscript.echo "Error detected. Description : " & Err.description 
	if objWorkbook <> nothing then objWorkbook.close false
	if objExcel<>nothing then objExcel.quit
end if
'objExcel.Quit
wscript.echo "Generated!"
wscript.echo ""
